### ISSUE TITLE
Does not work on OS X

### ISSUE THREAD

**Issue by mitchell-johnson** [rgerganov/footswitch#1]
Due to limitations with the libusb package on os x footswitch does not seem to work unfortunately. I begun to try to code around it but basically it requires not using the libusb libraries. 

Specifically footswitch returns:

libusb: 0.025330 info [darwin_open] device open for access
libusb: 0.025748 error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access cannot claim interface, error: LIBUSB_ERROR_ACCESS [init(), footswitch.c:79]

When trying to run any command under footswitch. I have posted a [how to](https://github.com/alevchuk/vim-clutch/issues/15) for os x users over on the vim clutch page to get a foot pedal working under os x.

**Comment by surajrav** [comment]
I just made the programming work (see pull request: https://github.com/rgerganov/footswitch/pull/14) on my mac. I stuck to libusb and managed to do so not claiming or releasing the device (works just fine i have tested it on the following product from amazon: http://www.amazon.com/gp/product/B00CK1BKZQ?psc=1&redirect=true&ref_=oh_aui_detailpage_o00_s00)

**Comment by rgerganov** [comment]
I have switched from libusb to hidapi which supports OSX. Let me know if you find any issues.
