### ISSUE TITLE
Lsusb finds footswitch, but cli tool does not

### ISSUE THREAD

**Issue by geertendoornenbal** [rgerganov/footswitch#16]
Hi,

Using lsusb -d 0c45:7403 I get a response with a footswitch.

However, when I use footswitch -r it says cannot find footswitch..
With some looking around, I suspect the hid_open_path is going wrong..

What can I do to fix this?

**Comment by rgerganov** [comment]
Did you install the udev rules? You need them to run footswitch with non-root users.

**Comment by geertendoornenbal** [comment]
No, I did not, this was not mentioned in your readme..
But running `sudo footswitch` would also work?

**Comment by rgerganov** [comment]
The udev rules are installed with `sudo make install`. Running `sudo footswitch` should also work.

**Comment by geertendoornenbal** [comment]
Thanks, with `sudo` it does work.
I did do `sudo make install` btw.
