### ISSUE TITLE
Support to execute bash script

### ISSUE THREAD

**Issue by Mte90** [rgerganov/footswitch#32]
I want to get a foot switch but I want that are configurable by a script.
As example when I press a switch I want to execute a bash script that can check what window has the focus and do specific things.
In that way I can use also for other application then only VIM.

**Comment by rgerganov** [comment]
The way to do this is to program the switch to emit a key combination (for example Ctrl+F7) and then make your desktop environment to execute a bash script when this combination is pressed.

**Comment by Mte90** [comment]
Yes is another option but seems an hack of another hack.

**Comment by rgerganov** [comment]
Launching shell scripts is not what this program is supposed to do.
