### ISSUE TITLE
Version numbers?

### ISSUE THREAD

**Issue by c704710** [rgerganov/footswitch#41]
Many GNU/Linux distros require versions for packaging. Where do I find version information for footswitch OR shall I just timestamp it (ie: 2018.07.31.11.30)? Either way, please make it clear in the docs.

**Comment by kenhys** [comment]
For Debian packaging, it is good enough to add versioned tag such as v1.0 or something because GitHub generates tar.gz archive.

**Comment by rgerganov** [comment]
I have created a v1.0 tag, the bits can be downloaded from the "Releases" section.
