### ISSUE TITLE
Configure a Scythe pedal

### ISSUE THREAD

**Issue by laspic** [rgerganov/footswitch#5]
I'd like to configure a Scythe pedal. 

I follow (successfully) the instructions to install your utility by github. And I get : 

```
$ footswitch -r
cannot find footswitch with VID:PID=c45:7403 [init(), footswitch.c:85]
```

It's not surprising, because : 

```
$ lsusb
Bus 004 Device 004: ID 0426:3011 Integrated Device Technology, Inc.
```

So, is it really impossible ? Or is there a trick I can test ?

**Comment by maz-1** [comment]
I found this: https://bitbucket.org/xemexys/usb_footswitch_driver/wiki/Home

**Comment by eisenlaub** [comment]
Could you add support for the Scythe Pedal given that the sources to the programming software for the Scythe pedal are available? They can be downloaded here: ftp://ftp.scythe-eu.com/Software/USB-Foot-Switch-II/Alternative_Programming_Software.zip

**Comment by teto** [comment]
I bouth the tripedal from scithe while in Europe, I believe it got sent from Germany. I never got around to setup it though :'(

**Comment by sblondon** [comment]
For info, I bought a Scythe 'usb triple foot switch 2' from ldlc.com (a european online reseller company).
```lsusb``` detects it with id 0426:3011. It's the values found by laspic too.

**Comment by victorhahncastell** [comment]
@rgerganov I notice your last comment was quite some while ago -- are you by any chance still interested in implementing support for Scythe? I'll be glad to send you one as a gift.

**Comment by rgerganov** [comment]
@victorhahncastell Yes, that would be awesome. Please contact me on email and I will send you a shipping address. Thanks!

**Comment by Mte90** [comment]
I see that a Scythe is available on amazon in europe.

Keep updated about that because I am evaluating to buy one!

**Comment by Mte90** [comment]
Any updates for that? We can do a crowdfounding in case for the pedal.

**Comment by rgerganov** [comment]
I have received the hardware from Victor but I have been very busy with other stuff. I will post updates here as soon as I start working on this.

**Comment by Mte90** [comment]
Cool, so I can order my copy and wait like a baby for Christmas :-D

**Comment by rgerganov** [comment]
I have added support for Scythe switches:
https://github.com/rgerganov/footswitch/pull/33

The functionality is a little bit different from PCsensor, so I decided to create a separate binary `scythe` for them. The changes are in the `scythe` branch and after doing some more tests, I will merge them to master. Let me know if you have any issues.

**Comment by victorhahncastell** [comment]
Awesome! Thanks so much @rgerganov, can't wait to try this out :-)

**Comment by hanwin** [comment]
alexandercurtis:
If you want to run it under Linux as a normal user check your udev rules.
Check the file 19-footswitch.rules

**Comment by Mte90** [comment]
I have problems on debian https://github.com/rgerganov/footswitch/issues/36
maybe someone can help on that :-)
