### ISSUE TITLE
run shell script when button is pressed

### ISSUE THREAD

**Issue by saiballo** [rgerganov/footswitch#52]
is it possible to run a shell script when button is pressed even the screen is locked?

now i achive this goal mapping a key shortcut but it does not run when screen is locked

**Comment by rgerganov** [comment]
Well, the whole idea of running a screen lock is to prevent unauthorized access which includes executing programs. I don't think there is an easy way to achieve this.

**Comment by saiballo** [comment]
well, you are right... ok thank you!
