### ISSUE TITLE
Reseting the foot switch

### ISSUE THREAD

**Issue by nuarbnitram** [rgerganov/footswitch#54]
Is it possible to reset the foot switch to the behaviour it had before a command was used?

Background: Before I used footswitch, the foot switch caused a keystroke that lasted as long as the switch was pressed. After using footswitch, the switch apparently only sends a short keystroke.

I can switch back to the defaut b key with `footswitch -s b`, but it has not the original behaviour.

**Comment by rgerganov** [comment]
For the repeat behavior, you have to program a single key like this:
`./footswitch -k b`
