### ISSUE TITLE
Right Ctrl only?

### ISSUE THREAD

**Issue by CorsairF4U** [rgerganov/footswitch#55]
Trying to find a way to program right ctrl key only?
I've not found a way yet.

Thanks.

**Comment by rgerganov** [comment]
This has been requested before (issue #43) but I don't know how to do it. Sorry.

**Comment by hanwin** [comment]
Maybe this will push you in right direction
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

**Comment by rgerganov** [comment]
Does `footswitch -k Control_R` work for you?

**Comment by rgerganov** [comment]
Implemented with commit 1225425e66013646cd68d02009b7bec6136e5006
